### ISSUE TITLE
Join forces?

### ISSUE THREAD

**Issue by iwasrobbed** [chriseidhof/commonmark-swift#21]
Hey Chris 👋 Any chance you want to join forces on [Down](https://github.com/iwasrobbed/Down)? 

I'd like to find a few others willing to help maintain it since it ended up being one of the most starred Swift wrappers for CommonMark. I don't use it very often, but I just want to have a wrapper for the community to use and help flesh out simple/performant APIs.

**Comment by chriseidhof** [comment]
Hey @iwasrobbed ! Thanks for the offer. I'd be a very bad maintainer (I wasn't good at maintaining open source projects, and now with a baby in the family I'm pretty sure I'd be even worse). The main reason we keep this lib open-source is because it's an example in Advanced Swift. So I'm not aiming for this to be the most starred library, it's mostly there for educational purposes.

That said, I do think some of the techniques (an AST, and especially being able to transform the AST) could be very interesting for your lib as well, and I wouldn't mind at all if we copy all that functionality into Down. 

BTW, we also did some work on rendering markdown to attributed strings using a form of stylesheets, you might find that interesting as well?

**Comment by iwasrobbed** [comment]
I hear ya re: maintaining open source libs and thanks for the suggestions! I'll dig around once I get some free time

Take care 👋

**Comment by chriseidhof** [comment]
@iwasrobbed awesome! Also happy to jump on a hangout sometime to tell you what I like about the stuff we've built (and how we use it in production).
